### ISSUE TITLE
ccfank无法正常使用

### ISSUE THREAD

**Issue by Eddie-hy** [WenyanLiu/CCFrank4dblp#100]
今天早上开始好像ccfank就无法正常使用，不知道是兼容问题还是其他问题？

**Comment by DanyangLihhh** [comment]
我也遇到了这个问题，不知道您解决了没有

**Comment by Eddie-hy** [comment]
> 我也遇到了这个问题，不知道您解决了没有

应该不是个人问题，我们实验室都用不了了，我笔记本上也不行
