### ISSUE TITLE
Identify POPL(CCF A ) as  PACM PL(CCF C)

### ISSUE THREAD

**Issue by SeddonShen** [WenyanLiu/CCFrank4dblp#116]
Identify Proceedings of the ACM on Programming Languages(POPL, CCF A) as Proceedings of the ACM on Programming Languages (PACM PL, CCF C)
For Example：[RustBelt: Securing the foundations of the Rust programming language](https://dl.acm.org/doi/abs/10.1145/3158154)
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/81d5ac54-27b5-4ce5-96b2-abdf73791585">
The problem has been around for a long time, Thanks for noticing!

Best regards.

**Comment by MarkLee131** [comment]
Yes, this issue also applied to OOPSLA (CCF-A).

**Comment by WenyanLiu** [comment]
Dear all,
Thank you for bringing this issue to our attention.
Thanks to @MarkLee131's pull request, the issue has been resolved.
The fix has now been merged and is currently awaiting review for release in the app store.
If you encounter any other issues, please feel free to report them.
Thank you for your attention, and wish you all the best in your academic endeavors.

**Comment by WenyanLiu** [comment]
@all-contributors please add @SeddonShen for bug
