### ISSUE TITLE
把CCF A 的文章分類為CCF None 了 （TIP) 

### ISSUE THREAD

**Issue by allanchan339** [WenyanLiu/CCFrank4dblp#119]
舉個例子
<img width="617" alt="image" src="https://github.com/user-attachments/assets/97629808-b4c8-4753-9404-b3d1c1553dd1">
在我看來是因為 transactions 變為了 Transactions ，然後就分不出來了

**Comment by lovelxc** [comment]
![image](https://github.com/user-attachments/assets/2c96db22-e541-4e14-9512-f5f8962e40f7)
依家應該可以了
