### ISSUE TITLE
2024年的ASE显示CCF-None

### ISSUE THREAD

**Issue by shaoyuyoung** [WenyanLiu/CCFrank4dblp#121]
下面这篇文章
![image](https://github.com/user-attachments/assets/fe4a5cb3-d68a-4d14-bfdb-5db9ae740aee)
似乎所有的24年ASE都存在这个问题

**Comment by lovelxc** [comment]
盲猜 dblp 没收录吧

**Comment by shaoyuyoung** [comment]
似乎确实是DBLP还没来记得收录。但这似乎不是很合理，因为google scholar都能显示出来发表的刊物了，但是却被标记为None

**Comment by MarkLee131** [comment]
>但这似乎不是很合理，因为google scholar都能显示出来发表的刊物了，但是却被标记为None

google scholar相对于dblp特殊的地方是，作者可以自己新建和更新google scholar的论文信息。
而且，目前ccfrank的逻辑是解析dblp api返回的论文信息来判断ccf rank。这样也比直接解析google scholar上的信息更靠谱一些（?） :)

**Comment by shaoyuyoung** [comment]
谢谢，我认为这是一个合理的逻辑 :)
