### ISSUE TITLE
Pattern Recognition 期刊识别错误

### ISSUE THREAD

**Issue by zhuye88** [WenyanLiu/CCFrank4dblp#16]
Pattern Recognition 识别错误 应该是CCF B但是显示为 CCF none.

**Comment by WenyanLiu** [comment]
感谢您的指正！

在针对该期刊修改匹配规则前，请容许我确认下：
《Pattern Recognition》在《[中国计算机学会推荐国际学术刊物](https://www.ccf.org.cn/Academic_Evaluation/AI/)》（见 人工智能 B 类第 21 项）的地址是[http://dblp.uni-trier.de/db/conf/par/](http://dblp.uni-trier.de/db/conf/par/)，
实际上在 dblp 中，该期刊的地址应改成 [https://dblp.org/db/journals/pr/index.html](https://dblp.org/db/journals/pr/index.html)，对吗？

我不太熟悉这个期刊，感谢您的帮助！

**Comment by zhuye88** [comment]
谢谢你的回复，CCF的目前使用的地址（http://dblp.uni-trier.de/db/conf/par/）是错误的。这个期刊官网是https://www.journals.elsevier.com/pattern-recognition，你的地址（https://dblp.org/db/journals/pr/index.html）是可以跳转过去的。

**Comment by WenyanLiu** [comment]
v3.1.2 修复了该期刊的地址错误，已同步上传应用商店等待审核。

感谢使用，祝您工作顺利~

如果方便的话，请给我个 star 以示鼓励吧 <3 感谢~

**Comment by WenyanLiu** [comment]
@all-contributors please add @zhuye88 for bug
