### ISSUE TITLE
谷歌学术识别存在问题

### ISSUE THREAD

**Issue by linwhitehat** [WenyanLiu/CCFrank4dblp#18]
CCF-C 期刊 CLSR在谷歌学术中没有正确识别，但在dblp中是正确识别的。建议修正谷歌学术环境下的识别结果。
![image](https://user-images.githubusercontent.com/20349381/112476991-73683580-8dad-11eb-945a-0c8b727cd80a.png)

**Comment by WenyanLiu** [comment]
感谢您的建议！

请允许我解释一下插件支持谷歌学术的思路：
- 在谷歌学术中，用户填写期刊/会议，可能出现全称/缩写不一致的情况，直接匹配名称导致错误率极高；
- 在dblp中，期刊/会议是规整的（见 [How accurate is the data in dblp?](https://dblp.org/faq/13500484.html)）。
那么，我的解决办法是：
1. 当我们使用谷歌学术时，调用dblp的[API](https://dblp.org/faq/13501473.html)，向其发送搜索结果中“论文名+第一作者的姓氏”；
2. 根据dblp响应的期刊/会议，为谷歌学术打上tag。

目前，存在的问题（也就是您反馈的情况）：
由于dblp期刊/会议的更新比谷歌学术慢，当谷歌学术向dblp查询文章，且dblp尚未更新期刊/会议数据库时，dblp的响应结果错误地显示文章没有发表在已知的CCF列表中，即被打上CCF none的标签。

回到我们这个issue本身，（2021年5月19日）dblp已同步“Mapping”所在CLSR的第40卷。
所以，这篇文章在谷歌学术上已经显示CCF C啦~
可是，后续还可能有其他文章会出现类似的情况，我目前没有好的思路来解决这个问题。

再次感谢您的反馈！

**Comment by linwhitehat** [comment]
> 感谢您的建议！
> 
> 请允许我解释一下插件支持谷歌学术的思路：
> 
> * 在谷歌学术中，用户填写期刊/会议，可能出现全称/缩写不一致的情况，直接匹配名称导致错误率极高；
> * 在dblp中，期刊/会议是规整的（见 [How accurate is the data in dblp?](https://dblp.org/faq/13500484.html)）。
>   那么，我的解决办法是：
> 
> 1. 当我们使用谷歌学术时，调用dblp的[API](https://dblp.org/faq/13501473.html)，向其发送搜索结果中“论文名+第一作者的姓氏”；
> 2. 根据dblp响应的期刊/会议，为谷歌学术打上tag。
> 
> 目前，存在的问题（也就是您反馈的情况）：
> 由于dblp期刊/会议的更新比谷歌学术慢，当谷歌学术向dblp查询文章，且dblp尚未更新期刊/会议数据库时，dblp的响应结果错误地显示文章没有发表在已知的CCF列表中，即被打上CCF none的标签。
> 
> 回到我们这个issue本身，（2021年5月19日）dblp已同步“Mapping”所在CLSR的第40卷。
> 所以，这篇文章在谷歌学术上已经显示CCF C啦~
> 可是，后续还可能有其他文章会出现类似的情况，我目前没有好的思路来解决这个问题。
> 
> 再次感谢您的反馈！

辛苦作者，谷歌学术确实存在很多不匹配的情况，主要是关键词之间的组合可能不太统一，例如这个
![image](https://user-images.githubusercontent.com/20349381/127763862-574b7839-b89d-4083-a3f6-84e8763bf68c.png)
这是一篇usenix security的论文《Defeating DNN-Based Traffic Analysis Systems in Real-Time With Blind Adversarial Perturbations》，但是没有被正确识别，对比其他正常识别的情况，是会议名称存在特殊符号。
![image](https://user-images.githubusercontent.com/20349381/127763894-07dd7cec-8f59-4b40-9310-b56ff504bfc5.png)
针对谷歌学术上的这种问题，个人建议试试覆盖率更高的正则表达能不能让匹配效果更好。

**Comment by WenyanLiu** [comment]
感谢反馈！

dblp已于2021年9月16日上传“Defeating ...”所属30th USENIX Security Symposium 2021的论文集。
这篇文章在谷歌学术上被标记为CCF A啦~

后续如果有其他我没有考虑到的情况，欢迎您的反馈～
感谢一直以来的使用和关注！

**Comment by WenyanLiu** [comment]
@all-contributors please add @linwhitehat for bug
