### ISSUE TITLE
Not working on Firefox/Google Scholar

### ISSUE THREAD

**Issue by zshhans** [WenyanLiu/CCFrank4dblp#22]
![](https://user-images.githubusercontent.com/25279261/126025348-a249f4f4-78a5-477d-923e-33ca60be81dc.png)

Windows 10
Firefox 90.0
Extension installed from Firefox add-ons market.

Working well on dblp, but showing nothing on google scholar in Firefox.
Working well for both dblp and google scholar in Chrome on the same PC.

**Comment by zshhans** [comment]
Bug located:
The extension doesn't have permission to access `dblp.org` from google scholar pages, so the `xhr.responseText` is always `<empty string>`.

Fix:
Add the following permission statement to `manifest.json`
```json
  "permissions": [
    "*://dblp.org/*"
  ]
```

Tested OK with my Firefox environment.

**Comment by WenyanLiu** [comment]
Many thanks to @zshhans!

Fixed with the help of your code ~

Updated in Firefox.

Appreciate your contributions!
May you excel at your research!

**Comment by WenyanLiu** [comment]
@all-contributors please add @zshhans for bug and code
