### ISSUE TITLE
与其他插件的冲突，谷歌学术的个人页面中的文章会出现重复的Label

### ISSUE THREAD

**Issue by Fanchao-Qi** [WenyanLiu/CCFrank4dblp#25]
感谢开发这款插件，非常实用！

我同时在使用AI/ML Papers with Code Everywhere - CatalyzeX [[link](https://chrome.google.com/webstore/detail/aiml-papers-with-code-eve/aikkeehnlfpamidigaffhfmgbkdeheil)] 这款插件来显示论文的代码链接。

但是在使用过程中发现了一个问题，发现了一个小冲突，即在谷歌学术的个人页面中的文章可能会出现重复的CCF等级标签（我尝试关闭上面的那个插件就一切正常了），例如：

![image](https://user-images.githubusercontent.com/12222818/128847617-e27aed42-65b2-43cb-8027-0d6d86b84ecd.png)

如果方便的话希望能解决一下，谢谢。

**Comment by WenyanLiu** [comment]
感谢您的反馈！

已在 3.2.4 版本中修复该错误，同时已上传 Chrome 和 Firefox 应用商店等待审核。

感谢使用，祝科研顺利~

如果方便的话，请给我个 star 以示鼓励叭~ 谢谢~

**Comment by WenyanLiu** [comment]
@all-contributors please add @Fanchao-Qi for bug
