### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by kevyn-zhang** [WenyanLiu/CCFrank4dblp#3]
如图，搜索列表显示ccf B类，结果查了一下这个期刊是ccf none
如果不是偶然点进去看了，还真不知道这个判断错了
![Snipaste_2020-11-03_20-30-01](https://user-images.githubusercontent.com/73885971/97985556-643f1600-1e13-11eb-8b78-7b8e9bf82b69.png)

![Snipaste_2020-11-03_20-29-31](https://user-images.githubusercontent.com/73885971/97985493-4bcefb80-1e13-11eb-951e-b220cc13d8ae.png)

**Comment by WenyanLiu** [comment]
感谢 @kevyn-zhang 的指正！
该期刊应为CCF B类，见《[中国计算机学会推荐国际学术刊物](https://www.ccf.org.cn/Academic_Evaluation/TCSE_SS_PDL/)》（软件工程/系统软件/程序设计语言）B类第13项。
因此，搜索结果页上的标记是正确的，期刊页标记错误的原因是 CCF 刊物全称中的“冒号”与 dblp 中的“连字符”匹配失败。

- [ ] 修复由“连字符”引起的错误。

再次感谢指正！

**Comment by WenyanLiu** [comment]
已修复。
感谢使用，学业进步哟~
如果这个小插件还OK的话，请给我个star以示鼓励吧 <3 谢谢~
