### ISSUE TITLE
请求增加Semantic Scholar的支持

### ISSUE THREAD

**Issue by bo233** [WenyanLiu/CCFrank4dblp#32]
你好，这个插件给我提供了很大的帮助，但是我平时经常使用Semantic Scholar，想请问作者能否增加对其的支持，谢谢！

**Comment by WenyanLiu** [comment]
很开心看到插件有用！

我刚刚探索了下 Semantic Scholar，引用的功能做得很棒，谢谢您告诉我这个搜索引擎！

我看了下，Semantic Scholar 的 Journals & Conference 域比较规整，我将会在校对其命名规则后，增加对 Semantic Scholar 的支持。

感谢使用，祝学业有成！

**Comment by WenyanLiu** [comment]
您好，已增加对 Semantic Scholar 上 CCF 推荐会议的支持。
在 Semantic Scholar 上期刊（目前看到的大部分情况）使用的是全称，与 CCF 推荐列表有一些出入，我正在校对，需要一些时间。

支持 Semantic Scholar 上会议标记的插件已上传应用商店等待审核，我会尽快增加对期刊的支持。

再次感谢您的使用～

**Comment by bo233** [comment]
万分感谢！作者大大辛苦！

**Comment by WenyanLiu** [comment]
您好，在 Semantic Scholar 上也支持对期刊的 CCF 标记啦～

正在等各应用商店审核新版本。

后续使用过程中如有新的建议，欢迎反馈。

再次感谢您的关注，祝科研顺利哟～

**Comment by WenyanLiu** [comment]
@all-contributors please add @bo233 for platform
