### ISSUE TITLE
CCF rank list has updated

### ISSUE THREAD

**Issue by ViTsing** [WenyanLiu/CCFrank4dblp#48]
See the new CCF-rank list in https://www.ccf.org.cn/Academic_Evaluation/By_category/
Thank you for this valuable project～

**Comment by WenyanLiu** [comment]
@all-contributors please add @ViTsing for data

**Comment by WenyanLiu** [comment]
感谢您的提醒！

目录数据已更新，且已上传应用商店等待审核～

感谢使用，祝一切都好～

如果可以的话，请给我star以示鼓励 <3 谢谢！
