### ISSUE TITLE
会议未正确识别（PPOPP）

### ISSUE THREAD

**Issue by realstolz** [WenyanLiu/CCFrank4dblp#5]

**Comment by WenyanLiu** [comment]
感谢 @realstolz 的反馈！
该会议为CCF A类，见《[中国计算机学会推荐国际学术刊物](https://www.ccf.org.cn/Academic_Evaluation/ARCH_DCP_SS/)》（计算机体系结构/并行与分布计算/存储系统）A类第1项。
> [其中](https://www.ccf.org.cn/Academic_Evaluation/By_category/)，会议论文指“Full paper”或“Regular paper”（正式发表的长文），对于会议上其他形式发表的论文如Short paper、Demo paper、Technical Brief、Summary以及作为伴随会议的Workshop等不计入目录考虑的范围。

我的搜索结果页上标记是正确显示的。
![PPoPP](https://user-images.githubusercontent.com/16554557/101355064-09488500-38d1-11eb-9f9c-45753f84341e.png)

我将关闭这个issue。如果您觉得仍然有问题，欢迎Reopen。

感谢使用，再次感谢反馈！祝工作顺利~

**Comment by realstolz** [comment]
![image](https://user-images.githubusercontent.com/1779861/101370132-102cc300-38e4-11eb-8f95-e0f69315a7ee.png)

**Comment by realstolz** [comment]
PPoPP vs. PPOPP ??

**Comment by WenyanLiu** [comment]
感谢您的指正！

不好意思，我没有注意到：在dblp的搜索结果中，2018年及以前该会议的名称是“PPOPP”，2019年起该会议的名称是“PPoPP”。
非常抱歉~

我将reopen该issue。

- [ ] 即将在小版本更新中修复由“区分大小写”引起的错误。
- [ ] 即将在大版本更新中升级会议/期刊匹配规则，即“全称/简称匹配”->“网址匹配”。

再次感谢指正！

**Comment by WenyanLiu** [comment]
已在v2.0中修复此类错误，同时已上传新版本至平台等待审核。

再次感谢使用，祝工作顺利哟~
