### ISSUE TITLE
HPCA识别错误

### ISSUE THREAD

**Issue by sdtsztom** [WenyanLiu/CCFrank4dblp#53]
HPCA识别为CCF none (应该为CCF A)
HPCA的dblp主页为: https://dblp.uni-trier.de/db/conf/hpca/index.html

**Comment by sdtsztom** [comment]
目前被判别为CCF A(实际应该是CCF None?)的HPCA(https://dblp.uni-trier.de/db/conf/cnhpca/index.html)，其全称为"International Conference on High-Performance Computing and Applications" (见https://link.springer.com/book/10.1007/978-3-319-32557-6)

CCF A的HPCA全称的最后一个单词为Architecture，两者应该仅缩写相同，并无其他联系。

**Comment by WenyanLiu** [comment]
感谢您的指正和说明！<3

我晚上回去以后尽快改好～

**Comment by WenyanLiu** [comment]
@all-contributors please add @sdtsztom for data
