### ISSUE TITLE
MICRO识别错误

### ISSUE THREAD

**Issue by sdtsztom** [WenyanLiu/CCFrank4dblp#57]
现在被识别为CCF A的IEEE Micro (https://dblp.org/db/journals/micro/index.html) 是一个journal， 应该为CCF None

事实上为CCF A（目前为CCF None）的IEEE/ACM International Symposium on Microarchitecture，简写MICRO，是一个conference，地址为https://dblp.org/db/conf/micro/index.html，无论是名称、类型、链接地址都与《中国计算机学会推荐国际学术会议和期刊目录》中的记录相符。

**Comment by sdtsztom** [comment]
等等，我再确认一下

**Comment by WenyanLiu** [comment]
感谢您的说明！

请允许我再确认下，CCF推荐目录（[https://www.ccf.org.cn/Academic_Evaluation/ARCH_DCP_SS/](https://www.ccf.org.cn/Academic_Evaluation/ARCH_DCP_SS/)）中MICRO的地址不是图中的[journals/micro/](https://dblp.org/db/journals/micro/index.html)，而应该改为[/conf/micro/](https://dblp.org/db/conf/micro/index.html)，对吗？
![image](https://user-images.githubusercontent.com/16554557/228550937-997ab446-5db2-457b-a0b6-9e13c755ca98.png)

谢谢您的解答～

**Comment by sdtsztom** [comment]
是的

**Comment by sdtsztom** [comment]
虽然刚发现网页中是journal，但是供下载的pdf中一直都是conf，无论是2022的版本还是2019的版本。conf的那个肯定是CCF A。我小概率不确定的只是journal的那个和conf的那个有无联系。不过目前来看，我没发现有什么明显联系。

**Comment by WenyanLiu** [comment]
感谢说明！

晚上我来更正～谢谢～

**Comment by WenyanLiu** [comment]
@all-contributors please add @sdtsztom  for data

**Comment by WenyanLiu** [comment]
MICRO的地址已经更正啦，应用商店们正在审核。

感谢多次的指正~祝万事顺遂！
