### ISSUE TITLE
dblp上IoTJ（IEEE Internet of Things Journal）显示为CCF None，应该为CCF C类期刊

### ISSUE THREAD

**Issue by ailego** [WenyanLiu/CCFrank4dblp#59]
![1681899512008](https://user-images.githubusercontent.com/19545901/233045515-0ecad48b-998f-45b2-a5f1-d4def6f7e6bd.jpg)
原因应该是页面显示为“IEEE Internet Things J. ”。

**Comment by ailego** [comment]
似乎没有起作用 :)

**Comment by WenyanLiu** [comment]
感谢指正！

已修复，同时正在应用商店等待审核~

祝一切顺利~

如果可以的话，请给我个star以示鼓励吧 <3 谢谢～
