### ISSUE TITLE
支持firefox？

### ISSUE THREAD

**Issue by junwei-wang** [WenyanLiu/CCFrank4dblp#6]

**Comment by WenyanLiu** [comment]
您好，CCFrank正在Mozilla开发者中心等待审核，敬请赐候~
![ccfrank](https://user-images.githubusercontent.com/16554557/101565333-c9d08480-3a07-11eb-9726-3d19253443fa.png)

**Comment by WenyanLiu** [comment]
CCFrank已上架~
[https://addons.mozilla.org/zh-CN/firefox/addon/ccfrank/](https://addons.mozilla.org/zh-CN/firefox/addon/ccfrank/)

因为我平时用Chrome，所以对CCFrank在Firefox上的表现关注较少。如果在后续使用过程中有问题，欢迎再次反馈。

感谢关注，祝工作顺利~
如果这个小插件在新浏览器上也能给您提供方便的话，请star给我个鼓励吧 <3 感谢~
