### ISSUE TITLE
谷歌学术部分文章CCF等级显示不正常

### ISSUE THREAD

**Issue by Sumsky21** [WenyanLiu/CCFrank4dblp#60]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/58537872/233293196-644a0815-a899-4023-bd10-ec9514b7c250.png">

本机是win11 Edge扩展
如图，很多文章后面出现了重复多个相同的标记

**Comment by WenyanLiu** [comment]
@all-contributors please add @Sumsky21 for bug
