### ISSUE TITLE
部分会议无法显示

### ISSUE THREAD

**Issue by junqi-ma** [WenyanLiu/CCFrank4dblp#61]
普适计算会议UbiComp录取的文章统一发表于ACM会刊 Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies 上，因此目前无法在Google Scholar和DBLP上显示

**Comment by lovelxc** [comment]
能不能列几个文章，并说明他们应该显示什么等级？

**Comment by junqi-ma** [comment]
应该为CCF A
文章：
[1]  RESEARCH-ARTICLE SHARE ON Ensembles of Deep LSTM Learners for Activity Recognition using Wearables. IMWUT/UbiComp 2017
[2] LoRa Backscatter: Enabling The Vision of Ubiquitous Connectivity. IMUWT/UbiComp 2017
[3] IndoTrack: Device-Free Indoor Human Tracking with Commodity Wi-Fi. IMUWT/UbiComp 2017

**Comment by lovelxc** [comment]
我看了一下，据[北大计算机](https://cs.pku.edu.cn/info/1304/3144.htm) 说：

> 从2017 年起开始采用新的发表方式，每年的会议文章由 IMWUT (Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies) 期刊录用，并邀请全部作者参会。

"journals/imwut" 似乎就是从2017之后，开始”成为“UbiComp这个A会的，那么应该增加一个虚空A刊 IMWUT 来显示他是CCF A等级

实际上，我个人认为从2017之后 UbiComp==IMWUT，甚至于IMWUT > UbiComp，因为在dblp的数据中，UbiComp2017之后的文章几乎都是不超过5页的，和 IMWUT 的质量没法比

**Comment by junqi-ma** [comment]
您关于2017年后UbiComp/IMWUT关系的总结非常准确，增加“虚空A刊”的做法也很合理。我完全同意您的意见

**Comment by WenyanLiu** [comment]
@all-contributors please add @junqi-ma for data

**Comment by WenyanLiu** [comment]
感谢指正！

新版本已上传到应用商店等待审核啦~

祝学业顺利~

如果可以的话，请给我个star以示鼓励吧 <3 谢谢～
