### ISSUE TITLE
数据中USENIX Security和HotSec的URL重复，导致CCF-A USENIX Security被误标为CCF-C

### ISSUE THREAD

**Issue by ifzh** [WenyanLiu/CCFrank4dblp#7]
数据中USENIX Security和HotSec的URL重复，导致CCF-A USENIX Security被误标为CCF-C

**Comment by WenyanLiu** [comment]
感谢指正~
这里出错了，对不起！谢谢帮忙分析出错原因~
我这几天也发现AsiaCCS和CCS的URL重复，前者被误标为CCF-A，在想解决办法。

在把匹配规则更改成URL匹配后，我还发现了其他问题：
不应被计入CCF范围的Workshop论文也被标记为所在主会的排名。

而原本的按照人工校验字符串匹配也有些问题，例如：
会议更名（如NIPS->NeurIPS）、会议同缩写/同名（SAC<-Selected Areas in Cryptography Workshop/ACM Symposium On Applied Computing）、dblp修改命名规则（我可能需要1-2天的时间核验，如果正好赶上其他DDL更新会更慢）等。

所以，我在想是不是有其他更好的办法来完成这件事，如有，望不吝赐教~

- [ ] 即将回退匹配规则至字符串匹配。

再次感谢指正！

**Comment by ifzh** [comment]
一点不成熟的建议：

观察到会议主页（如“/db/conf/asiaccs/index.html”）和某一次具体会议的页面（如："/db/conf/ccs/asiaccs2020.html"）URL不同。

- URL匹配时，首先判断是否是会议主页，再判断是否是某一次具体会议的页面；
- 论文匹配时，根据其后跟随的当次会议的页面进行匹配，如图
![image](https://user-images.githubusercontent.com/11475849/102426890-33c1dd00-404b-11eb-9141-39671baaf88b.png)

不知道这样是否可行。也感谢提供这么实用的工具！

**Comment by linwhitehat** [comment]
> 感谢指正~
> 这里出错了，对不起！谢谢帮忙分析出错原因~
> 我这几天也发现AsiaCCS和CCS的URL重复，前者被误标为CCF-A，在想解决办法。
> 
> 在把匹配规则更改成URL匹配后，我还发现了其他问题：
> 不应被计入CCF范围的Workshop论文也被标记为所在主会的排名。
> 
> 而原本的按照人工校验字符串匹配也有些问题，例如：
> 会议更名（如NIPS->NeurIPS）、会议同缩写/同名（SAC<-Selected Areas in Cryptography Workshop/ACM Symposium On Applied Computing）、dblp修改命名规则（我可能需要1-2天的时间核验，如果正好赶上其他DDL更新会更慢）等。
> 
> 所以，我在想是不是有其他更好的办法来完成这件事，如有，望不吝赐教~
> 
> * [ ]  即将回退匹配规则至字符串匹配。
> 
> 再次感谢指正！

我觉得是不是不依靠单一模式的匹配会更准确一些，在匹配的会议URL中对重复的URL做二次匹配，避免出现重复地址导致会议等级错误的问题。这么做的简单思路是：
1、不用完全修改现有的匹配模式；
2、只需要对少数重复的会议URL做二次处理，在二次处理时使用字符串匹配来保证会议之间的区分。

**Comment by WenyanLiu** [comment]
感谢两位的帮助~❤

根据大家的建议，目前会议/期刊主页和论文出处的匹配方式已做出如 @ifzh 所说的调整。也感谢 @linwhitehat 的思路，帮助我快速对字典内容做出调整~

v3.1.1扩充了字典，修复了由URL重复引起的错误，同时已上传应用店等待审核。

感谢使用，感谢你们的指点，科研顺利哟~
如果可以的话，请star给我鼓励吧 <3 谢谢~
